#!/bin/bash


aliaes_file="$HOME/.dalias"

if [ ! -f "$aliaes_file" ]; then
  touch "$aliaes_file"
fi

case $1 in
	ls)
		cat $aliaes_file
		;;
	save)
		echo $2 `pwd` >> $aliaes_file
		;;
	cd)
    dest=$(cat $aliaes_file | grep "^${2} " | head -1 | cut -d " " -f 2)
		if [ -n "$dest" ]; then
			cd $dest
		else
			echo "$2 not found"
		fi
		;;
	rm)
		sed -i '' "/^$2 /d" $aliaes_file
		;;
  get)
    dest=$(cat $aliaes_file | grep "^${2} " | head -1 | cut -d " " -f 2)
		if [ -n "$dest" ]; then
			echo $dest
		else
			echo "$2 not found"
		fi
    ;;
  clean)
    while IFS= read -r line; do
      dest=$(echo "$line" | cut -d " " -f 2)
      alias=$(echo "$line" | cut -d " " -f 1)
      if [ ! -e $dest ]
      then
        dalias rm $alias
      fi
    done < $aliaes_file
    ;;
esac
