#!/bin/bash

aliaes_file="$HOME/.dalias"

if [ ! -f "$aliaes_file" ]; then
	touch "$aliaes_file"
fi

case $1 in
	ls)
		cat $aliaes_file
		;;
	save)
		echo $2 `pwd` >> $aliaes_file
		;;
	cd)
		dest=$(cat $aliaes_file | grep $2 | sed -e "s/^[A-Za-z0-9\.\_\-]* //")
		if [ -n "$dest" ]; then
			cd $dest
		else
			echo "$2 not found"
		fi
		;;
	rm)
		sed -i '' "/^$2 /d" $aliaes_file
		;;
esac
